remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Luca Scarpelli
description: Data Engineer | Multi-cloud ETL | Python | SQL

show_downloads: false

# Social links
github_username: lucascrp
linkedin_url: https://www.linkedin.com/in/luca-scarpelli-a46b84193
