theme: jekyll-theme-minimal

title: Luca Scarpelli
description: Data Engineer | Multi-cloud ETL | Python | SQL

show_downloads: false

# Social links
github_username: lucascrp
linkedin_url: https://www.linkedin.com/in/luca-scarpelli-a46b84193
